
package userInterface.nurseSchoolHead;

import business.EcoSystem;
import business.networkpkg.Network;
import business.organizationpkg.AmbulanceOrganization;
import business.organizationpkg.EmergencyOrganization;
import business.userAccountpkg.UserAccount;
import business.workQueuepkg.DoctorWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shravyagunda
 */

//this is the NurseHeadProcessRequestAreaJPanel
public class NurseHeadProcessRequestAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NurseHeadProcessRequestAreaJPanel
     */
    private JPanel userProcessContainer;
    private DoctorWorkRequest request;
 
    private  EcoSystem ecoSystem;
    private EmergencyOrganization emergencyOrg;
    private AmbulanceOrganization ambOrg;
    private UserAccount userAccount;
    public NurseHeadProcessRequestAreaJPanel(JPanel userProcessContainer, DoctorWorkRequest request, EcoSystem ecoSystem, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.ecoSystem = ecoSystem;
        this.userAccount = userAccount;
        resultComboBox.removeAllItems();
        resultComboBox.addItem(DoctorWorkRequest.REQUEST_APPROVED);
        resultComboBox.addItem(DoctorWorkRequest.REQUEST_REJECT);
        
        populateNetworkComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        submitJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        resultComboBox = new javax.swing.JComboBox();
        backJButton = new javax.swing.JButton();
        assignNetworkCombo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, -1));

        jLabel1.setText("Request Result");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 125, -1, -1));

        jLabel7.setFont(new java.awt.Font("Malayalam MN", 3, 24)); // NOI18N
        jLabel7.setText("Process Work Request:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 42, 300, -1));

        resultComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(resultComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 122, 163, -1));

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 401, -1, -1));

        assignNetworkCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        assignNetworkCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignNetworkComboActionPerformed(evt);
            }
        });
        jPanel1.add(assignNetworkCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 163, -1));

        jLabel2.setText("Select Network");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 100, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finalopaquebg.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-168, -113, 1300, 900));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 760, 630));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, 0));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finalopaquebg.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 1300, 900));
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        
        Network net = (Network)assignNetworkCombo.getSelectedItem();
        request.setStatus(DoctorWorkRequest.REQUEST_COMPLETED);
        
        System.out.print("Request status");
        System.out.println(request.getStatus());
        request.setResolveDate(new Date());
        request.setTestResult((String)resultComboBox.getSelectedItem());
       
        request.getSender().setNetwork(net);
        System.out.print("Request approved or no");
        System.out.println(request.getTestResult());
        if(request.getTestResult().equals(DoctorWorkRequest.REQUEST_APPROVED))
        {
            request.getSender().setEnabled(true);
            System.out.println(request.getSender().getUserName());

        }
    }//GEN-LAST:event_submitJButtonActionPerformed
 private void populateNetworkComboBox(){
        
        assignNetworkCombo.removeAllItems();
         if(ecoSystem.getNetworkList().isEmpty())
        {
        JOptionPane.showMessageDialog(null, "Networks does not exist! Please create networks.");  
         return;        
        }
        assignNetworkCombo.addItem("Please assign a Network");
        
           
        for(Network network : ecoSystem.getNetworkList())
        {
             assignNetworkCombo.addItem(network);
        }

        }
    
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        NurseHeadWorkAreaJPanel nurseWorkAreaPanel = (NurseHeadWorkAreaJPanel) component;
        nurseWorkAreaPanel.populateWorkReqJTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void assignNetworkComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignNetworkComboActionPerformed

    }//GEN-LAST:event_assignNetworkComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox assignNetworkCombo;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox resultComboBox;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
