
package userInterface.patient;

import business.common.DOBValidation;
import business.common.EmailValidation;
import business.common.NumberValidation;
import business.common.StringValidation;
import business.common.GetOrganizations;
import business.personpkg.Person;
import business.userAccountpkg.UserAccount;
import business.userAccountpkg.UserAccountDirectory;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

//this is the UpdatePatientProfile
public class UpdatePatientProfile extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private UserAccount userAccount; 
    private Person person;
    private UserAccountDirectory userAccountDirectory;
    
    /**
     * Creates new form ViewVolunteerProfile
     */
    public UpdatePatientProfile(JPanel userProcessContainer, UserAccount userAccount, UserAccountDirectory userAccountDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        person = userAccount.getPerson();
        this.userAccountDirectory = userAccountDirectory;
        DateFormat dateformat = new SimpleDateFormat("MM/dd/yyyy");
                
        firstNameField.setText(person.getFirstName());
        lastNameField.setText(person.getLastName());
        dobField.setText(dateformat.format(person.getDob()));
        genderComboBox.setSelectedItem(person.getGender());
        addressField2.setText(person.getAddress1());
        townField.setText(person.getTown());
        zipCodeField.setText(person.getZipCode());
        emailIDField.setText(person.getEmailId());
        userNameTxtField.setText(userAccount.getUserName());

        
        addInputVerifiers();
        
        
   }
    
    private void addInputVerifiers() {
          
        InputVerifier stringValidation = new StringValidation();
        firstNameField.setInputVerifier(stringValidation);
        lastNameField.setInputVerifier(stringValidation);
        addressField2.setInputVerifier(stringValidation);
        townField.setInputVerifier(stringValidation);
        addressField2.setInputVerifier(stringValidation);
        userNameTxtField.setInputVerifier(stringValidation);
        
        
        InputVerifier dobValidtion = new DOBValidation();
        dobField.setInputVerifier(dobValidtion);
        
        InputVerifier numberValidation = new NumberValidation();
        zipCodeField.setInputVerifier(numberValidation);
        
        
        
       InputVerifier emailValidtion = new EmailValidation();
        emailIDField.setInputVerifier(emailValidtion);
   
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageEnt = new javax.swing.JLabel();
        emailID = new javax.swing.JLabel();
        emailIDField = new javax.swing.JTextField();
        areaCode = new javax.swing.JLabel();
        userNameTxtField = new javax.swing.JTextField();
        firstName = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        updateJButton = new javax.swing.JButton();
        saveJButton = new javax.swing.JButton();
        LastName = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        lastNameField = new javax.swing.JTextField();
        dateOfBirth = new javax.swing.JLabel();
        town = new javax.swing.JLabel();
        townField = new javax.swing.JTextField();
        zipCode = new javax.swing.JLabel();
        zipCodeField = new javax.swing.JTextField();
        dobField = new javax.swing.JFormattedTextField();
        address2 = new javax.swing.JLabel();
        addressField2 = new javax.swing.JTextField();
        manageEnt1 = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox();
        viewYourProfile2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        manageEnt.setFont(new java.awt.Font("Malayalam MN", 3, 24)); // NOI18N
        manageEnt.setText("Welcome to Heart Help");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailID.setText("Email Address:");
        add(emailID, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 101, -1));

        emailIDField.setEditable(false);
        emailIDField.setEnabled(false);
        add(emailIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 174, -1));

        areaCode.setText("User Name:");
        add(areaCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 760, -1, -1));

        userNameTxtField.setEditable(false);
        userNameTxtField.setEnabled(false);
        add(userNameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 746, 184, -1));

        firstName.setText("First Name:");
        add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 194, -1));

        firstNameField.setEditable(false);
        firstNameField.setEnabled(false);
        add(firstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 184, -1));

        updateJButton.setText("Update");
        updateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJButtonActionPerformed(evt);
            }
        });
        add(updateJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 847, -1, -1));

        saveJButton.setText("Save");
        saveJButton.setEnabled(false);
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButtonActionPerformed(evt);
            }
        });
        add(saveJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 847, -1, -1));

        LastName.setText("Last Name:");
        add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 194, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 843, -1, -1));

        lastNameField.setEditable(false);
        lastNameField.setEnabled(false);
        add(lastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 184, -1));

        dateOfBirth.setText("Date Of Birth (MM/DD/YYYY):");
        add(dateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 194, -1));

        town.setText("Town/City: ");
        add(town, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 656, -1, -1));

        townField.setEditable(false);
        townField.setEnabled(false);
        add(townField, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 653, 184, -1));

        zipCode.setText("Zip Code:");
        add(zipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 697, 78, -1));

        zipCodeField.setEditable(false);
        zipCodeField.setEnabled(false);
        add(zipCodeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 694, 184, -1));

        dobField.setEnabled(false);
        add(dobField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 184, -1));

        address2.setText("Address Line2 : ");
        add(address2, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 613, 107, -1));

        addressField2.setEnabled(false);
        add(addressField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 610, 184, -1));

        manageEnt1.setFont(new java.awt.Font("Malayalam MN", 3, 24)); // NOI18N
        manageEnt1.setText("Patient Details");
        add(manageEnt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 13, 200, 70));

        gender.setText("Gender:");
        add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, -1, -1));

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose gender", "Female", "Male", "Transgender", "Unknown" }));
        genderComboBox.setEnabled(false);
        add(genderComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 184, -1));

        viewYourProfile2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        viewYourProfile2.setText("Address: ");
        add(viewYourProfile2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/opaque-mask1.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -3, 1300, 910));
    }// </editor-fold>//GEN-END:initComponents

    private void updateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJButtonActionPerformed

        firstNameField.setEnabled(true);
        lastNameField.setEnabled(true);
        dobField.setEnabled(true);
        genderComboBox.setEnabled(true);
        addressField2.setEnabled(true);
        townField.setEnabled(true);
        zipCodeField.setEnabled(true);
        userNameTxtField.setEnabled(true);
        saveJButton.setEnabled(true);
        updateJButton.setEnabled(false);
        firstNameField.setEditable(true);
        lastNameField.setEditable(true);
        dobField.setEditable(true);
         addressField2.setEditable(true);
        townField.setEditable(true);
        zipCodeField.setEditable(true);
        userNameTxtField.setEditable(true);
    }//GEN-LAST:event_updateJButtonActionPerformed

    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButtonActionPerformed

       
        if(firstNameField.getText()!= null && !firstNameField.getText().isEmpty() &&
            lastNameField.getText()!= null && !lastNameField.getText().isEmpty() &&
           addressField2.getText()!=null && !addressField2.getText().isEmpty() &&
            townField.getText()!=null && !townField.getText().isEmpty() &&
            emailIDField.getText()!=null && !emailIDField.getText().isEmpty() &&
             userNameTxtField.getText()!=null && !userNameTxtField.getText().isEmpty() 
                && genderComboBox.getSelectedIndex()>=1 && dobField.getText()!=null && 
                !dobField.getText().isEmpty() && 
             zipCodeField.getText()!=null && !zipCodeField.getText().isEmpty())
        {
            try
            {
                 if(!(userAccount.getUserName().equals(userNameTxtField.getText()))&&!(userAccountDirectory.checkIfUsernameIsUnique(userNameTxtField.getText())))
                    {
                        JOptionPane.showMessageDialog(null, "User Name already exists!, Please Enter valid user name","warning", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                 
                
                  Date dateOfBirthVal = new SimpleDateFormat("MM/dd/yyyy").parse(dobField.getText()) ;
                  int age = GetOrganizations.calculateAge(dateOfBirthVal);
                   if(age<12)
                    {
                    JOptionPane.showMessageDialog(null, "Your age does not qualify to be a Volunteer!","warning", JOptionPane.WARNING_MESSAGE);
                     return;
                    }
                    person.setFirstName(firstNameField.getText());
                    person.setLastName(lastNameField.getText());
                    person.setAddress1(addressField2.getText());
                    person.setTown(townField.getText());
                    person.setZipCode(zipCodeField.getText());
                    userAccount.setUserName(userNameTxtField.getText());
                    person.setDob(dateOfBirthVal);
            }
            catch(NumberFormatException nfe)
            {
                JOptionPane.showMessageDialog(this, "Please Enter valid details", "warning",JOptionPane.WARNING_MESSAGE);
            return;
            }
            catch(ParseException pe)
            {
            JOptionPane.showMessageDialog(this, "Please Enter valid details", "warning",JOptionPane.WARNING_MESSAGE);
            return; 
            }
           
             JOptionPane.showMessageDialog(null, "Your Profile has been updated successfully", "success", JOptionPane.PLAIN_MESSAGE);
                updateJButton.setEnabled(true);
                saveJButton.setEnabled(false);
                firstNameField.setEnabled(false);
                lastNameField.setEnabled(false);
                addressField2.setEnabled(false);
                dobField.setEnabled(false);
                genderComboBox.setEnabled(false);
                addressField2.setEnabled(false);
                townField.setEnabled(false);
                zipCodeField.setEnabled(false);
                emailIDField.setEnabled(false);
                userNameTxtField.setEnabled(false);
         }
        else
        {
            JOptionPane.showMessageDialog(null, "Please Enter data in all the fields");
        }

    }//GEN-LAST:event_saveJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel address2;
    private javax.swing.JTextField addressField2;
    private javax.swing.JLabel areaCode;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel dateOfBirth;
    private javax.swing.JFormattedTextField dobField;
    private javax.swing.JLabel emailID;
    private javax.swing.JTextField emailIDField;
    private javax.swing.JLabel firstName;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel gender;
    private javax.swing.JComboBox genderComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel manageEnt;
    private javax.swing.JLabel manageEnt1;
    private javax.swing.JButton saveJButton;
    private javax.swing.JLabel town;
    private javax.swing.JTextField townField;
    private javax.swing.JButton updateJButton;
    private javax.swing.JTextField userNameTxtField;
    private javax.swing.JLabel viewYourProfile2;
    private javax.swing.JLabel zipCode;
    private javax.swing.JTextField zipCodeField;
    // End of variables declaration//GEN-END:variables
}
