/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.doctor;


import business.common.*;
import business.personpkg.Person;
import business.userAccountpkg.UserAccount;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


//this is the CreateDoctorProfileJPanel
public class CreateDoctorProfileJPanel extends javax.swing.JPanel {
     private JPanel userProcessContainer;
    private UserAccount userAccount;
   
    public CreateDoctorProfileJPanel(JPanel userProcessContainer, UserAccount account) {
        initComponents();
          this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        addInputVerifiers();
        docNameField.setText(userAccount.getPerson().getName());
    }
    
      private void addInputVerifiers() {
          
        InputVerifier stringValidation = new StringValidation();
        docNameField.setInputVerifier(stringValidation);
        docaddressField.setInputVerifier(stringValidation);
        townField.setInputVerifier(stringValidation);
        occupationField.setInputVerifier(stringValidation);
        
        InputVerifier dobValidtion = new DOBValidation();
        docDobField.setInputVerifier(dobValidtion);
        
        InputVerifier numberValidation = new NumberValidation();
        zipCodeField.setInputVerifier(numberValidation);
        
     
        
        InputVerifier emailValidtion = new EmailValidation();
        emailIDField.setInputVerifier(emailValidtion);
     
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zipCodeField = new javax.swing.JTextField();
        docNameField = new javax.swing.JTextField();
        Name = new javax.swing.JLabel();
        createYourProfile = new javax.swing.JLabel();
        docDobField = new javax.swing.JFormattedTextField();
        backJButton = new javax.swing.JButton();
        createProfileButton = new javax.swing.JButton();
        zipCode = new javax.swing.JLabel();
        townField = new javax.swing.JTextField();
        emailIDField = new javax.swing.JTextField();
        town = new javax.swing.JLabel();
        docaddressField = new javax.swing.JTextField();
        emailID = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        occupationField = new javax.swing.JTextField();
        dateOfBirth = new javax.swing.JLabel();
        occupation = new javax.swing.JLabel();
        manageEnt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(zipCodeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 700, 184, -1));

        docNameField.setEditable(false);
        docNameField.setEnabled(false);
        add(docNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 184, -1));

        Name.setText("Full Name:");
        add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 194, -1));

        createYourProfile.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        createYourProfile.setText("Create Your Profile");
        add(createYourProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 185, -1));
        add(docDobField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 184, -1));

        backJButton.setText("<< back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 856, -1, -1));

        createProfileButton.setText("Create Profile ");
        createProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProfileButtonActionPerformed(evt);
            }
        });
        add(createProfileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(736, 856, 146, -1));

        zipCode.setText("Zip Code:");
        add(zipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 710, 78, -1));
        add(townField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 184, -1));
        add(emailIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 610, 184, -1));

        town.setText("Town/City: ");
        add(town, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, -1, -1));
        add(docaddressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 184, -1));

        emailID.setText("Email Address:");
        add(emailID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 620, 101, -1));

        address.setText("Address: ");
        add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 194, -1));
        add(occupationField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, 184, -1));

        dateOfBirth.setText("Date Of Birth (MM/DD/YYYY):");
        add(dateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 194, -1));

        occupation.setText("Occupation:");
        add(occupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, -1, -1));

        manageEnt.setFont(new java.awt.Font("Malayalam MN", 3, 24)); // NOI18N
        manageEnt.setText("Doctor Profile");
        add(manageEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 281, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finalopaquebg.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -3, 1300, 910));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void createProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProfileButtonActionPerformed
        Person person = userAccount.getPerson();
        if( docaddressField.getText()==null || docaddressField.getText().trim().isEmpty() ||
            townField.getText()==null || townField.getText().trim().isEmpty() ||
            occupationField.getText()==null || occupationField.getText().trim().isEmpty() ||
            emailIDField.getText()==null || emailIDField.getText().trim().isEmpty() ||
            docDobField.getText()==null || docDobField.getText().trim().isEmpty() ||
            zipCodeField.getText()==null || zipCodeField.getText().trim().isEmpty() )
        {
            JOptionPane.showMessageDialog(null, "Please Enter data in all fields");
           return;
        }
        try
        {
        DateFormat dateFormat =  new SimpleDateFormat("MM/dd/yyyy");
        Date date = new Date();
        Date dob =  dateFormat.parse(docDobField.getText());
        if(dob.after(date) || dob.equals(date))
        {
         JOptionPane.showMessageDialog(null, "Please Enter valid Date of Birth");
           return;    
        }
        
            person.setDob(dateFormat.parse(docDobField.getText()));
            person.setAddress1(docaddressField.getText());
            person.setTown(townField.getText());
           
            person.setZipCode(zipCodeField.getText());
            person.setEmailId(emailIDField.getText());
          

            
            resetFields();
        }
        catch(ParseException pe)
        {
            JOptionPane.showMessageDialog(null, "Please Enter valid date of Birth!");
        }
        catch(NumberFormatException nfe)
        {
          JOptionPane.showMessageDialog(null, "Please Enter valid number!");
             
        }
        catch(Exception e)
        {  
            JOptionPane.showMessageDialog(null, "Please Enter valid data in all the fields");
            
        }
    }//GEN-LAST:event_createProfileButtonActionPerformed

    public void resetFields()
{
    docNameField.setText("");
    docDobField.setText("");
    docaddressField.setText("");
    townField.setText("");
    occupationField.setText("");
    zipCodeField.setText("");
    emailIDField.setText("");
   
    
    
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JLabel address;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton createProfileButton;
    private javax.swing.JLabel createYourProfile;
    private javax.swing.JLabel dateOfBirth;
    private javax.swing.JFormattedTextField docDobField;
    private javax.swing.JTextField docNameField;
    private javax.swing.JTextField docaddressField;
    private javax.swing.JLabel emailID;
    private javax.swing.JTextField emailIDField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel manageEnt;
    private javax.swing.JLabel occupation;
    private javax.swing.JTextField occupationField;
    private javax.swing.JLabel town;
    private javax.swing.JTextField townField;
    private javax.swing.JLabel zipCode;
    private javax.swing.JTextField zipCodeField;
    // End of variables declaration//GEN-END:variables
}
