/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.patient;

import business.EcoSystem;
import business.enterprisepkg.*;
import business.networkpkg.Network;
import business.organizationpkg.*;
import business.personpkg.*;
import business.userAccountpkg.UserAccount;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JPanel;

//this is the ViewPatientProfile
public class ViewPatientProfile extends javax.swing.JPanel {
    
     private JPanel userProcessContainer;
    private UserAccount userAccount; 
    private EcoSystem ecoSystem;
    private Person person;
    private Patient patient;
    
  
    /**
     * Creates new form ViewVolunteerProfile
     */
    public ViewPatientProfile(JPanel userProcessContainer, UserAccount userAccount, EcoSystem ecoSystem) {
        initComponents();
        
         this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        person = userAccount.getPerson();
        
        this.ecoSystem = ecoSystem;
        ArrayList<Patient> patientList =null;
        Patient patient = null;
       
        ArrayList<Network> NetworkDir = ecoSystem.getNetworkList();
        ArrayList<Enterprise> enterpriseList = null;
        
        Enterprise enterprise; 
        
        //give for loop
         for(Network network:NetworkDir)
         {
             System.out.print(network.getCountry());
             enterpriseList = network.getEnterpriseDirectory().getEnterpriseList();
            
         
        
        for( Enterprise enprise: enterpriseList)
        {
    
            if((enprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Hospital)))
            {
                
               for (Organization organization : enprise.getOrganizationDirectory().getOrganizationList()) 
               {
                     if(organization.getName().equals("Patient Organization"))
                    {
                        ArrayList<Patient> patients = organization.getPersonDirectory().getPatientList();
  
        
                         for(Patient pat: patients)
                      {
                          
                          
                          if(pat.getName().matches(person.getName()))
                             {
                
                                 patient = pat;
 
                              }
                      }   

                    }
        
               }
 
            }
        }    
     }
     
        DateFormat form = new SimpleDateFormat("MM/dd/yyyy");
                
        firstNameField.setText(person.getFirstName());
        lastNameField.setText(person.getLastName());
        dobField.setText(form.format(person.getDob()));
        genderComboBox.setSelectedItem(person.getGender());
        addressField1.setText(person.getAddress1());
        townField.setText(person.getTown());
        zipCodeField.setText(person.getZipCode());
        emailIDField.setText(person.getEmailId());
        
        spo2Txt.setText(Float.toString(patient.getSpo2Level()));
        if(patient.isIsCovid()==true){
            covidTxt.setText("Positive");
        
        }
        else
            covidTxt.setText("Negative");
        
        tempTxt.setText(Float.toString(patient.getTemperature()));
        
        if(patient.isIsCough()==true){
            coughTxt.setText("Yes");
        
        }
        else
            coughTxt.setText("No");
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewYourProfile2 = new javax.swing.JLabel();
        covidTxt = new javax.swing.JTextField();
        LastName = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        lastNameField = new javax.swing.JTextField();
        firstName = new javax.swing.JLabel();
        dateOfBirth = new javax.swing.JLabel();
        phoneNumber = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        town = new javax.swing.JLabel();
        addressField1 = new javax.swing.JTextField();
        townField = new javax.swing.JTextField();
        zipCode = new javax.swing.JLabel();
        zipCodeField = new javax.swing.JTextField();
        dobField = new javax.swing.JFormattedTextField();
        manageEnt1 = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox();
        viewYourProfile1 = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        emailID = new javax.swing.JLabel();
        emailIDField = new javax.swing.JTextField();
        spo2Txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tempTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        coughTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewYourProfile2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        viewYourProfile2.setText("Address: ");
        add(viewYourProfile2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, -1, -1));

        covidTxt.setEditable(false);
        covidTxt.setEnabled(false);
        covidTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                covidTxtActionPerformed(evt);
            }
        });
        add(covidTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 140, 184, -1));

        LastName.setText("Last Name:");
        add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 194, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 750, -1, -1));

        lastNameField.setEditable(false);
        lastNameField.setEnabled(false);
        add(lastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 184, -1));

        firstName.setText("First Name:");
        add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 194, -1));

        dateOfBirth.setText("Date Of Birth (YYYY/MM/DD):");
        add(dateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 194, -1));

        phoneNumber.setText("SpO2");
        add(phoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 360, -1, -1));

        address.setText("Address Line1:");
        add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 590, 194, -1));

        town.setText("Town/City: ");
        add(town, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 650, -1, -1));

        addressField1.setEditable(false);
        addressField1.setEnabled(false);
        add(addressField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, 184, -1));

        townField.setEditable(false);
        townField.setEnabled(false);
        add(townField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 650, 184, -1));

        zipCode.setText("Zip Code:");
        add(zipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 710, 78, -1));

        zipCodeField.setEditable(false);
        zipCodeField.setEnabled(false);
        add(zipCodeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 710, 184, -1));

        dobField.setEnabled(false);
        add(dobField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 184, -1));

        manageEnt1.setFont(new java.awt.Font("Malayalam MN", 3, 24)); // NOI18N
        manageEnt1.setText("                                                  Patient");
        add(manageEnt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 650, 90));

        gender.setText("Gender:");
        add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, -1, -1));

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose gender", "Female", "Male", "Transgender", "Unknown" }));
        genderComboBox.setEnabled(false);
        add(genderComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 184, -1));

        viewYourProfile1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        add(viewYourProfile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 60, -1, -1));

        firstNameField.setEditable(false);
        firstNameField.setEnabled(false);
        add(firstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 184, -1));

        emailID.setText("Email Address:");
        add(emailID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 760, 101, -1));

        emailIDField.setEditable(false);
        emailIDField.setEnabled(false);
        add(emailIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 760, 184, -1));

        spo2Txt.setEditable(false);
        spo2Txt.setEnabled(false);
        spo2Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spo2TxtActionPerformed(evt);
            }
        });
        add(spo2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 350, 190, -1));

        jLabel1.setText("Covid");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, 50, 30));

        tempTxt.setEditable(false);
        tempTxt.setEnabled(false);
        tempTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempTxtActionPerformed(evt);
            }
        });
        add(tempTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 200, 189, -1));

        jLabel2.setText("Temperature");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 200, -1, -1));

        jLabel3.setText("Cough");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 270, 80, 30));

        coughTxt.setEditable(false);
        coughTxt.setEnabled(false);
        coughTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coughTxtActionPerformed(evt);
            }
        });
        add(coughTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 270, 189, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/opaque-mask1.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 910));
    }// </editor-fold>//GEN-END:initComponents

    private void covidTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_covidTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_covidTxtActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void spo2TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spo2TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spo2TxtActionPerformed

    private void tempTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempTxtActionPerformed

    private void coughTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coughTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coughTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel address;
    private javax.swing.JTextField addressField1;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField coughTxt;
    private javax.swing.JTextField covidTxt;
    private javax.swing.JLabel dateOfBirth;
    private javax.swing.JFormattedTextField dobField;
    private javax.swing.JLabel emailID;
    private javax.swing.JTextField emailIDField;
    private javax.swing.JLabel firstName;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel gender;
    private javax.swing.JComboBox genderComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel manageEnt1;
    private javax.swing.JLabel phoneNumber;
    private javax.swing.JTextField spo2Txt;
    private javax.swing.JTextField tempTxt;
    private javax.swing.JLabel town;
    private javax.swing.JTextField townField;
    private javax.swing.JLabel viewYourProfile1;
    private javax.swing.JLabel viewYourProfile2;
    private javax.swing.JLabel zipCode;
    private javax.swing.JTextField zipCodeField;
    // End of variables declaration//GEN-END:variables
}
