
package userInterface.nurse;

/**
 *
 * @author shravyagunda
 */

import business.userAccountpkg.UserAccount;
import business.workQueuepkg.*;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


//this is the ProcessNurseWorkRequestJPanel
public class ProcessNurseWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessNurseWorkRequestJPanel
     */
     private JPanel userProcessContainer;
    private NeedNurseWorkRequest request;
    private UserAccount userAccount;
    public ProcessNurseWorkRequestJPanel(JPanel userProcessContainer, NeedNurseWorkRequest request, UserAccount userAccount) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.userAccount = userAccount;
        
        populateResultComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        submitJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        resultComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 818, -1, -1));

        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 221, -1, -1));

        jLabel1.setText("Request Result");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 125, -1, -1));

        jLabel7.setFont(new java.awt.Font("Malayalam MN", 3, 24)); // NOI18N
        jLabel7.setText("Process Work Request:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 42, 300, -1));

        resultComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(resultComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 122, 163, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finalopaquebg.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -3, 1300, 900));
    }// </editor-fold>//GEN-END:initComponents
 public void populateResultComboBox()
    {
        resultComboBox.removeAllItems();
        resultComboBox.addItem(DoctorWorkRequest.REQUEST_ACCEPT);
        resultComboBox.addItem(DoctorWorkRequest.REQUEST_REJECT);
    }
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        NurseWorkAreaJPanel driverWorkAreaPanel = (NurseWorkAreaJPanel) component;
        driverWorkAreaPanel.populatenurseRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        if(resultComboBox.getSelectedIndex()<0 )
        {
            JOptionPane.showMessageDialog(null, "Please enter data in all fields", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        request.setNurseReqResult((String)resultComboBox.getSelectedItem());
        request.setStatus(DoctorWorkRequest.REQUEST_COMPLETED);
        request.setResolveDate(new Date());
        JOptionPane.showMessageDialog(null, "Request has been processed successfully", "success", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_submitJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox resultComboBox;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
