
package userInterface.nurse;

/**
 *
 * @author shravyagunda
 */
   

import business.EcoSystem;
import business.enterprisepkg.Enterprise;
import business.networkpkg.Network;
import business.organizationpkg.Organization;
import business.personpkg.*;
import business.userAccountpkg.UserAccount;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JPanel;


//this is the ViewNurseProfile
public class ViewNurseProfile extends javax.swing.JPanel {

    /**
     * Creates new form ViewNurseProfile
     */  private JPanel userProcessContainer;
    private UserAccount userAccount; 
    private EcoSystem ecoSystem;
    private Person person;
    private Patient patient;
    public ViewNurseProfile(JPanel userProcessContainer, UserAccount userAccount, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        person = userAccount.getPerson();
        this.ecoSystem = ecoSystem;
        
        ArrayList<Nurse> nurseList =null;
        Nurse nurse = null;
       
        ArrayList<Network> NetworkDir = ecoSystem.getNetworkList();
        ArrayList<Enterprise> enterpriseList = null;
        
        Enterprise enterprise; 
        
        //give for loop
         for(Network network:NetworkDir)
         {
             System.out.print(network.getCountry());
             enterpriseList = network.getEnterpriseDirectory().getEnterpriseList();
         
        for( Enterprise enprise: enterpriseList)
        {
            System.out.println("enterprise name" + enprise.getName());
            System.out.println("enterprise type" + enprise.getEnterpriseType());
             
            if(enprise.getEnterpriseType().equals(Enterprise.EnterpriseType.CoVolunteer))
            {
                
               for (Organization organization : enprise.getOrganizationDirectory().getOrganizationList()) 
               {
                      System.out.println("Organization name:" + organization.getName());
                    if(organization.getName().equals("Nurse School Organization"))
                    {
                        ArrayList<Nurse> nurses = organization.getPersonDirectory().getNurseList();
                        
                         for(Nurse nur: nurses)
                      {
                          System.out.print("Nrse name: "+nur.getName());
                          
                          if(nur.getName().matches(person.getName()))
                             {
                                 nurse=nur;
                             }
                       }   
                    }
               }
            }
        }
       }
        DateFormat form = new SimpleDateFormat("MM/dd/yyyy");
        
        firstNameField.setText(person.getFirstName());
        lastNameField.setText(person.getLastName());
        dobField.setText(form.format(person.getDob()));
        genderComboBox.setSelectedItem(person.getGender());
        addressField1.setText(person.getAddress1());
        townField.setText(person.getTown());
        zipCodeField.setText(person.getZipCode());
        emailIDField.setText(person.getEmailId());
        
        expTxt.setText(nurse.getExperience());
        degTxt.setText(nurse.getDegree());
        if(nurse.isPoscov())
            covidConYesRbtn.setSelected(true);
        else
            covidConNoRbtn.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewYourProfile1 = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        firstName = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        dateOfBirth = new javax.swing.JLabel();
        dobField = new javax.swing.JFormattedTextField();
        genderComboBox = new javax.swing.JComboBox();
        gender = new javax.swing.JLabel();
        viewYourProfile2 = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        addressField1 = new javax.swing.JTextField();
        town = new javax.swing.JLabel();
        zipCode = new javax.swing.JLabel();
        zipCodeField = new javax.swing.JTextField();
        townField = new javax.swing.JTextField();
        emailID = new javax.swing.JLabel();
        emailIDField = new javax.swing.JTextField();
        emailID2 = new javax.swing.JLabel();
        emailID1 = new javax.swing.JLabel();
        expTxt = new javax.swing.JTextField();
        degTxt = new javax.swing.JTextField();
        emailID3 = new javax.swing.JLabel();
        covidConYesRbtn = new javax.swing.JRadioButton();
        covidConNoRbtn = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewYourProfile1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        viewYourProfile1.setText("Nurse Profile:");
        add(viewYourProfile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 300, 40));

        firstNameField.setEditable(false);
        firstNameField.setEnabled(false);
        add(firstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 184, -1));

        firstName.setText("First Name:");
        add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 180, -1));

        LastName.setText("Last Name:");
        add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 180, -1));

        lastNameField.setEditable(false);
        lastNameField.setEnabled(false);
        add(lastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 184, -1));

        dateOfBirth.setText("Date Of Birth (YYYY/MM/DD):");
        add(dateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 180, -1));

        dobField.setEnabled(false);
        add(dobField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 184, -1));

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose gender", "Female", "Male", "Transgender", "Unknown" }));
        genderComboBox.setEnabled(false);
        add(genderComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 184, -1));

        gender.setText("Gender:");
        add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        viewYourProfile2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        viewYourProfile2.setText("Address: ");
        add(viewYourProfile2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, -1, -1));

        address.setText("Address Line1:");
        add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 670, 194, -1));

        addressField1.setEditable(false);
        addressField1.setEnabled(false);
        add(addressField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 670, 184, -1));

        town.setText("Town/City: ");
        add(town, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 750, -1, -1));

        zipCode.setText("Zip Code:");
        add(zipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, 78, -1));

        zipCodeField.setEditable(false);
        zipCodeField.setEnabled(false);
        add(zipCodeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 600, 184, -1));

        townField.setEditable(false);
        townField.setEnabled(false);
        add(townField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 730, 184, -1));

        emailID.setText("Email Address:");
        add(emailID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 101, -1));

        emailIDField.setEditable(false);
        emailIDField.setEnabled(false);
        add(emailIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 184, -1));

        emailID2.setText("Degree");
        add(emailID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, -1, -1));

        emailID1.setText("Experience");
        add(emailID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, -1, -1));

        expTxt.setEditable(false);
        add(expTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 100, 178, -1));
        add(degTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 170, 178, -1));

        emailID3.setText("In contact with Covid positive person in last 15 days?");
        add(emailID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, -1, -1));

        covidConYesRbtn.setText("Yes");
        add(covidConYesRbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, -1, -1));

        covidConNoRbtn.setText("No");
        add(covidConNoRbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 290, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finalopaquebg.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -3, 1300, 910));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel address;
    private javax.swing.JTextField addressField1;
    private javax.swing.JRadioButton covidConNoRbtn;
    private javax.swing.JRadioButton covidConYesRbtn;
    private javax.swing.JLabel dateOfBirth;
    private javax.swing.JTextField degTxt;
    private javax.swing.JFormattedTextField dobField;
    private javax.swing.JLabel emailID;
    private javax.swing.JLabel emailID1;
    private javax.swing.JLabel emailID2;
    private javax.swing.JLabel emailID3;
    private javax.swing.JTextField emailIDField;
    private javax.swing.JTextField expTxt;
    private javax.swing.JLabel firstName;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel gender;
    private javax.swing.JComboBox genderComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel town;
    private javax.swing.JTextField townField;
    private javax.swing.JLabel viewYourProfile1;
    private javax.swing.JLabel viewYourProfile2;
    private javax.swing.JLabel zipCode;
    private javax.swing.JTextField zipCodeField;
    // End of variables declaration//GEN-END:variables
}
